/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#49d7f4",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#a8edff",
        "inverse-on-surface": "#e9f2f8",
        "inverse-primary": "#49d7f4",
        "tertiary-fixed-dim": "#ebc23e",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#574500",
        "surface-container-highest": "#dbe4ea",
        "surface-dim": "#d2dbe1",
        "primary-fixed": "#a8edff",
        "tertiary": "#735c00",
        "on-primary-container": "#004e5b",
        "on-primary-fixed": "#001f26",
        "on-error": "#ffffff",
        "secondary-container": "#ebdcff",
        "error": "#ba1a1a",
        "surface-variant": "#dbe4ea",
        "inverse-surface": "#293236",
        "surface-container-high": "#e0e9ef",
        "on-surface-variant": "#334a50",
        "on-secondary-container": "#543589",
        "secondary": "#6d4ea2",
        "on-tertiary-fixed": "#241a00",
        "surface": "#f4faff",
        "tertiary-fixed": "#ffe087",
        "secondary-fixed-dim": "#d4bbff",
        "on-secondary-fixed-variant": "#543589",
        "surface-tint": "#006879",
        "primary": "#006879",
        "on-primary-fixed-variant": "#004e5b",
        "tertiary-container": "#ffe087",
        "surface-bright": "#f4faff",
        "surface-container": "#e6eff5",
        "on-tertiary-fixed-variant": "#574500",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#270058",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ebdcff",
        "background": "#f4faff",
        "on-primary": "#ffffff",
        "surface-container-low": "#ecf5fb",
        "outline-variant": "#b2cbd2",
        "on-background": "#141d21",
        "on-surface": "#141d21",
        "outline": "#637b81"
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Lexend", "sans-serif"],
        "label": ["Lexend", "sans-serif"],
        "lexend": ["Lexend", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"
      },
    },
  },
  plugins: [],
}
